### ISSUE TITLE
Install under Windows 10 always asks for the WIndows 10 SDK

### ISSUE THREAD

**Issue by louisvangeldrop** [serialport/node-serialport#2167]
### Summary of Problem

(Please answer all 3)

- I try to install at my Windows 10 pc
- The install fails. No Windows 10 SDK installed
- Simple install without the installation of the full Windows 10 SDK

### Code to Reproduce the Issue
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found.
Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\louis\node_module
s\@serialport\bindings\build\bindings.vcxproj]

```js
const serialport = new SerialPort(path)

// Code
```

### Versions, Operating System and Hardware

- SerialPort@?
- Node.js v12.16.1
- Windows
- Dell XPS

**Comment by GazHank** [comment]
I believe this is due to the build tools not being included in your Path environment variable.

If you are able to install one of the prebuilt binaries then you shouldn't need any of the build tooling.  If you want to build from source then you will probably need to update your path to include the required library files (unfortunately recent versions of VS don't seem to update the path as it gives you the opportunity to have multiple versions of the SDK on your machine without conflict).
