### ISSUE TITLE
Cannot open connection to USB-serial device

### ISSUE THREAD

**Issue by hazaart** [serialport/node-serialport#2262]
### Summary of Problem

I have a USB to serial (RS422) cable plugged into my Windows PC and would like to read the data from the serial device.
When opening the connection to the device using the device path found in Windows Device Manager I am getting an error the connection failed.

### Code to Reproduce the Issue
`var serialPort = new SerialPort("USB\\VID_0403&PID_6001\\A167E2HP");`

> Error: Opening USB\VID_0403&PID_6001\A167E2HP: Unknown error code 3
> Emitted 'error' event on SerialPort instance at:
>     at SerialPort._error

### Versions, Operating System and Hardware

- SerialPort@latest
- Node.js v? latest
- Windows? Linux? Mac? Windows
- Hardware and chipset? (Prolific/FTDI/Other). Cable is from FTDI.

**Comment by GazHank** [comment]
Hi @hazaart,

Are you only getting the error when trying to connect?  I.e. no issues when you try to list() the ports?

I think that on Windows you would usually reference the com port number e.g. COM3 to open the port in this way.  However you may want to try identifying the port using the vendor & product ID if possible rather than hard coding to a specific port.  I shared some example code in response to https://github.com/serialport/node-serialport/issues/2245 if that would be helpful to you too

Cheers

Gaz
