### ISSUE TITLE
100% CPU Utilization on OSX

### ISSUE THREAD

**Issue by planetclegg** [serialport/node-serialport#303]
The following program is a sample of connecting to an Arduino at 115200 baud and dumping the output to stdout using a pipe (streams):

```
var com = require("serialport");
var serial = new com.SerialPort("/dev/tty.usbmodemfa141", {  baudrate: 115200 });
serial.pipe(process.stdout);
```

The program works as expected, _however_ it pegs the CPU utilization at 100% and keeps it there.  The Arduino is sending small (~100 byte) messages 2-3 times per minute, so 99% of the time the serial connection is idle.  BTW, this is a highly stripped down version of the full app, to demonstrate the core issue.  This is on OS X 10.6.8, using a local install of serialport 1.3.1, running on node 0.10.25 (installed with homebrew).  

Some experiments: if I change the last line to "process.stdin.pipe(process.stdout);" but leave the serial connection on line 2, it also pegs the CPU.  If I then comment out the second line it runs at 0%.   Also, a roughly equivalent program written in Python with pyserial connected to the same Arduino doesn't have the same issue.

**Comment by bhaveshgohel** [comment]
@voodootikigod : No issue at all now, i have find out the problem was in my code, it was continuously checking the port for data by opening and closing port with different data-bit rates and was not waiting till the current port was closed or say it was not Synchronous in nature.

I have used  [async](https://github.com/caolan/async) library to make Synchronous functions calls in Asynchronous manner, so it will now wait for one proccess to complete or completely abort the execution if fails or whatever we need.

All is Well now. :+1:
