### ISSUE TITLE
Support for timeout

### ISSUE THREAD

**Issue by bodavid** [serialport/node-serialport#44]
I would appreciate support for timeout so that the buffer content is sent it the timeout is reached.

Thanks,
David

**Comment by chintanp** [comment]
@JayBeavers : What is that exactly supposed to mean - "Closing due to age:" ? Does the library have "timeout" support or not  ? 
If not, so you have any suggestions for how this can be achieved reliably ?

"serial" in python has this http://pyserial.readthedocs.org/en/latest/pyserial_api.html and it would be great to have something similar, as a project I am working on needs it.
