### ISSUE TITLE
"The Platform for project 'serial port.vcxproj' is invalid. Platform='x64'.

### ISSUE THREAD

**Issue by mick** [serialport/node-serialport#90]
This has been reported by a user of a project of my that use serialport. This is what I know so far:

When building on Windows 7 (or 8) 64 bit the following error:  "The Platform for project 'serial port.vcxproj' is invalid. Platform='x64'.

Windows 7 or 8 64bit
node js v0.8.9 (64 bit)
python 2.7.x
Visual Studio 2010 (or 2012, which I understand there are other possible issues with)
Windows 7 SDK 64bit

![Build Error](http://i.imgur.com/9yC4p.png)

**Comment by waterWang** [comment]
python 2.7.9 + nodejs 0.12.7 +npm 2.11.3 +windows 64 + VC++ Express 2010

err
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'hcaptha.vcxproj' is in
valid.  Platform='x64'. You may be seeing this message because you are trying t
o build a project without a solution file, and have specified a non-default Pla
tform that doesn't exist for this project. [C:\Users\adam\AppData\Roaming\npm\n
ode_modules\ccap\build\hcaptha.vcxproj]
?
